=head1 NAME

kurila13delta - what is new for Perl Kurila 1.3

=head1 DESCRIPTION

This document describes differences between Perl Kurila 0.2 and Perl Kurila 1.3

=head1 Highlights In Kurila 1.3

=over 4

=item *

Removal <*>, use glob("*") instead

=item *

Default C3 method resolution

=item *

Default "use strict 'subs'"

=item *

Integrate bleadperl changes

=back

=head1 Core Enhancements

=head2 Removal <*>, use glob("*") instead

The <'pattern'> glob operator, has been removed in favor of the "glob" function.

=head2 Default C3 method resolution

The default method resolution is not C3, see L<mro> for more information about
the C3 method resolution.

=head2 Default "use strict 'subs'"

By default "use strict 'subs'" is active. See L<strict> for what this means.

=head2 Internal bleadperl changes

bleadperl changes upto 31540 are integrated

=back

=head1 KNOWN BUGS

=head2 Documentation

Documention has not been updated for many of the changes for kurila.

=head2 Limited platform support

Perl Kurila has ony been tested/build for x86_64-linux-gnu-thread-multi platform.

=head1 SEE ALSO

The F<INSTALL> file for how to build Perl Kurila.

The F<README> file for general stuff.

The F<Artistic> and F<Copying> files for copyright information.

=head1 HISTORY

Written by Gerard Goossen <F<gerard@tty.nl>>.

=cut
