=head1 NAME

perlkurila -- description of Kurila

=head1 DESCRIPTION

Short description of what Perl Kurila is, and what its goals are.

=head2 What is Kurila?

Perl Kurila is a branch/fork of Perl 5.

=head2 Why?

To have a more evolving language without being hel back by backwards compatibility.
Kurila is intended with the goal of developing a new major Perl version.
Remove some ugly things, add some ugly things.
Cleanup source.

=head2 Backward compatibility

Kurila is not intended to be backwards compatible.
There is the p5kurila convert script which attempts to convert Perl 5 to
Perl Kurila.

=head2 Development

Development is currently only done by Gerard Goossen. Usin the git repository
at git://dev.tty.nl/perl

=head1 SEE ALSO

=over 4

=item L<kurila02delta> too see what has changed compared to Perl 5.

=back

=head1 AUTHOR

Gerard Goossen <gerard@tty.nl>
