/*  -*- buffer-read-only: t -*-
 *
 *    regcharclass.h
 *
 *    Copyright (C) 2007, by Larry Wall and others
 *
 *    You may distribute under the terms of either the GNU General Public
 *    License or the Artistic License, as specified in the README file.
 *
 * !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 * This file is built by Porting/regcharclass.pl.
 * (Generated at: Tue May  1 16:37:55 2007 GMT)
 * Any changes made here will be lost!
 */

/*
	LNBREAK: Line Break: \R

	"\x0D\x0A"      # CRLF - Network (Windows) line ending
	0x0A            # LF  | LINE FEED
	0x0B            # VT  | VERTICAL TAB
	0x0C            # FF  | FORM FEED
	0x0D            # CR  | CARRIAGE RETURN
	0x85            # NEL | NEXT LINE
	0x2028          # LINE SEPARATOR
	0x2029          # PARAGRAPH SEPARATOR
*/
/*** GENERATED CODE ***/
#define is_LNBREAK(s,is_utf8)                                               \
( ( ((U8*)s)[0]==13 ) ?                                                     \
    ( ( ((U8*)s)[1]==10 ) ? 2 : 1 ) :                                       \
  ( (10<=((U8*)s)[0] && ((U8*)s)[0]<=12) ? 1 :                              \
( (is_utf8) ?                                                               \
  ( ( ((U8*)s)[0]==194 ) ?                                                  \
    ( ( ((U8*)s)[1]==133 ) ? 2 : 0 ) :                                      \
  (((( ((U8*)s)[0]==226 ) && ( ((U8*)s)[1]==128 )) && ( ((U8*)s)[2]==168 || ((U8*)s)[2]==169 )) ? 3 : 0) ) :\
  ( ((U8*)s)[0]==133 ) ) ) )                                                

/*** GENERATED CODE ***/
#define is_LNBREAK_safe(s,e,is_utf8)                                        \
( ( (e) - (s) > 2 ) ?                                                       \
  ( ( ((U8*)s)[0]==13 ) ?                                                   \
    ( ( ((U8*)s)[1]==10 ) ? 2 : 1 ) :                                       \
  ( (10<=((U8*)s)[0] && ((U8*)s)[0]<=12) ? 1 :                              \
( (is_utf8) ?                                                               \
  ( ( ((U8*)s)[0]==194 ) ?                                                  \
    ( ( ((U8*)s)[1]==133 ) ? 2 : 0 ) :                                      \
  (((( ((U8*)s)[0]==226 ) && ( ((U8*)s)[1]==128 )) && ( ((U8*)s)[2]==168 || ((U8*)s)[2]==169 )) ? 3 : 0) ) :\
  ( ((U8*)s)[0]==133 ) ) ) ) :                                              \
( ( (e) - (s) > 1 ) ?                                                       \
  ( ( ((U8*)s)[0]==13 ) ?                                                   \
    ( ( ((U8*)s)[1]==10 ) ? 2 : 1 ) :                                       \
  ( (10<=((U8*)s)[0] && ((U8*)s)[0]<=12) ? 1 :                              \
( (is_utf8) ?                                                               \
  ((( ((U8*)s)[0]==194 ) && ( ((U8*)s)[1]==133 )) ? 2 : 0) :                \
  ( ((U8*)s)[0]==133 ) ) ) ) :                                              \
( ( (e) - (s) > 0 ) ?                                                       \
  ( (10<=((U8*)s)[0] && ((U8*)s)[0]<=13) ? 1 :                              \
( (!is_utf8) ?                                                              \
  ( ((U8*)s)[0]==133 ) : 0 ) ) : 0 ) ) )                                    

/*** GENERATED CODE ***/
#define is_LNBREAK_utf8(s)                                                  \
( ( ((U8*)s)[0]==194 ) ?                                                    \
    ( ( ((U8*)s)[1]==133 ) ? 2 : 0 ) :                                      \
  ( ( ((U8*)s)[0]==226 ) ?                                                  \
    ((( ((U8*)s)[1]==128 ) && ( ((U8*)s)[2]==168 || ((U8*)s)[2]==169 )) ? 3 : 0) :\
  ( ( ((U8*)s)[0]==13 ) ?                                                   \
    ( ( ((U8*)s)[1]==10 ) ? 2 : 1 ) :                                       \
  (10<=((U8*)s)[0] && ((U8*)s)[0]<=12) ) ) )                                

/*** GENERATED CODE ***/
#define is_LNBREAK_utf8_safe(s,e)                                           \
( ( (e) - (s) > 2 ) ?                                                       \
  ( ( ((U8*)s)[0]==194 ) ?                                                  \
    ( ( ((U8*)s)[1]==133 ) ? 2 : 0 ) :                                      \
  ( ( ((U8*)s)[0]==226 ) ?                                                  \
    ((( ((U8*)s)[1]==128 ) && ( ((U8*)s)[2]==168 || ((U8*)s)[2]==169 )) ? 3 : 0) :\
  ( ( ((U8*)s)[0]==13 ) ?                                                   \
    ( ( ((U8*)s)[1]==10 ) ? 2 : 1 ) :                                       \
  (10<=((U8*)s)[0] && ((U8*)s)[0]<=12) ) ) ) :                              \
( ( (e) - (s) > 1 ) ?                                                       \
  ( ( ((U8*)s)[0]==194 ) ?                                                  \
    ( ( ((U8*)s)[1]==133 ) ? 2 : 0 ) :                                      \
  ( ( ((U8*)s)[0]==13 ) ?                                                   \
    ( ( ((U8*)s)[1]==10 ) ? 2 : 1 ) :                                       \
  (10<=((U8*)s)[0] && ((U8*)s)[0]<=12) ) ) :                                \
( ( (e) - (s) > 0 ) ?                                                       \
  (10<=((U8*)s)[0] && ((U8*)s)[0]<=13) : 0 ) ) )                            

/*** GENERATED CODE ***/
#define is_LNBREAK_latin1(s)                                                \
( ( ((U8*)s)[0]==13 ) ?                                                     \
    ( ( ((U8*)s)[1]==10 ) ? 2 : 1 ) :                                       \
  ( (10<=((U8*)s)[0] && ((U8*)s)[0]<=12) || ((U8*)s)[0]==133 ) )            

/*** GENERATED CODE ***/
#define is_LNBREAK_latin1_safe(s,e)                                         \
( ( (e) - (s) > 1 ) ?                                                       \
  ( ( ((U8*)s)[0]==13 ) ?                                                   \
    ( ( ((U8*)s)[1]==10 ) ? 2 : 1 ) :                                       \
  ( (10<=((U8*)s)[0] && ((U8*)s)[0]<=12) || ((U8*)s)[0]==133 ) ) :          \
( ( (e) - (s) > 0 ) ?                                                       \
  ( (10<=((U8*)s)[0] && ((U8*)s)[0]<=13) || ((U8*)s)[0]==133 ) : 0 ) )      

/*** GENERATED CODE ***/
#define is_LNBREAK_cp(cp)                                                   \
( (10<=cp && cp<=13) || ( cp > 13 &&                                        \
( cp==133 || ( cp > 133 &&                                                  \
( cp==8232 || ( cp > 8232 &&                                                \
cp==8233 ) ) ) ) ) )                                                        

/* ex: set ro: */
