--- #YAML:1.0
name:                Devel-PPPort
version:             3.07
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              ~
distribution_type:   module
requires:     
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
