--- #YAML:1.0
name:                Devel-PPPort
version:             3.08
abstract:            Perl/Pollution/Portability
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Marcus Holland-Moritz <mhx@cpan.org>
distribution_type:   module
requires:     
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
