################################################################################
#
#            !!!!!   Do NOT edit this file directly!   !!!!!
#
#            Edit mktests.PL and/or parts/inc/sv_xpvf instead.
#
#  This file was automatically generated from the definition files in the
#  parts/inc/ subdirectory by mktests.PL. To learn more about how all this
#  works, please read the F<HACKERS> file that came with this distribution.
#
################################################################################

BEGIN {
  if ($ENV{'PERL_CORE'}) {
    chdir 't' if -d 't';
    @INC = ('../lib', '../ext/Devel/PPPort/t') if -d '../lib' && -d '../ext';
    require Config; Config->import;
    use vars '%Config';
    if (" $Config{'extensions'} " !~ m[ Devel/PPPort ]) {
      print "1..0 # Skip -- Perl configured without Devel::PPPort module\n";
      exit 0;
    }
  }
  else {
    unshift @INC, 't';
  }

  sub load {
    eval "use Test";
    require 'testutil.pl' if $@;
  }

  if (9) {
    load();
    plan(tests => 9);
  }
}

use Devel::PPPort;
use strict;
$^W = 1;

package Devel::PPPort;
use vars '@ISA';
require DynaLoader;
@ISA = qw(DynaLoader);
Devel::PPPort->bootstrap;

package main;

use Tie::Hash;
my %h;
tie %h, 'Tie::StdHash';
$h{foo} = 'foo-';
$h{bar} = '';

ok(&Devel::PPPort::vnewSVpvf(), 'Perl-42');
ok(&Devel::PPPort::sv_vcatpvf('1-2-3-'), '1-2-3-Perl-42');
ok(&Devel::PPPort::sv_vsetpvf('1-2-3-'), 'Perl-42');

&Devel::PPPort::sv_catpvf_mg($h{foo});
ok($h{foo}, 'foo-Perl-42');

&Devel::PPPort::Perl_sv_catpvf_mg($h{foo});
ok($h{foo}, 'foo-Perl-42-Perl-43');

&Devel::PPPort::sv_catpvf_mg_nocontext($h{foo});
ok($h{foo}, 'foo-Perl-42-Perl-43-Perl-44');

&Devel::PPPort::sv_setpvf_mg($h{bar});
ok($h{bar}, 'mhx-42');

&Devel::PPPort::Perl_sv_setpvf_mg($h{bar});
ok($h{bar}, 'foo-43');

&Devel::PPPort::sv_setpvf_mg_nocontext($h{bar});
ok($h{bar}, 'bar-44');

