#!/usr/local/bin/perl

use IO::Compress::Gzip < qw( $GzipError );
use strict ;
use warnings ;

die "Usage: gzappend gz-file file...\n"
    unless (nelems @ARGV) ;


my $output = shift @ARGV ;

@ARGV = @( '-' ) unless (nelems @ARGV) ;

my $gz = IO::Compress::Gzip->new( $output, Merge => 1)
     or die "Cannot open $output: $GzipError\n" ;

$gz->write( \ @ARGV )
     or die "Cannot open $output: $GzipError\n" ;

$gz->close;

    

