#!/usr/bin/perl -tw

use lib qw(t/lib);
use Test::More tests => 1;

my $warnings = '';
{
    local $SIG{__WARN__} = sub { $warnings .= $_[0]->{description} };
    kill 0, $^X;
}
like( $warnings, '/^Insecure dependency/',   '-t honored' );
